name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint on node 12 and ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint codebase
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    name: Test node 12 and ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test package
        run: yarn test
